package com.att.tdp.issueflow.domain.enums;

public enum AuditAction {
    CREATE,
    CREATE_PROJECT,
    CREATE_TICKET,
    UPDATE,
    UPDATE_PROJECT,
    UPDATE_TICKET,
    DELETE,
    DELETE_PROJECT,
    DELETE_TICKET,
    RESTORE,
    RESTORE_PROJECT,
    RESTORE_TICKET,
    LOGIN,
    LOGOUT,
    AUTO_ASSIGN,
    AUTO_ESCALATE,
    ADD_DEPENDENCY,
    REMOVE_DEPENDENCY,
    UPLOAD_ATTACHMENT,
    DELETE_ATTACHMENT,
    IMPORT
}
